---
# vars file for python
py2: 2 
python_link: https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg #https://www.python.org/downloads/macos/
python_pkg_name: "python-3.10.11-macos11.pkg"
python_full_version: "3.10.11"
python_vers_regex: 3\\.10\\.11